Implement discord bot example for typescript
GDATASoftwareAG/vaas pull request #5
Opened 2022-02-24 10:04 UTC by doxthree

Added typescript example for an discord bot, which deletes files with malicious content on an server, where the bot is running.

2022-02-24 10:23 UTC, unglaublicherdude approved these changes

2022-02-24 10:26 UTC, borisahrens approved these changes

2022-02-24 14:47 UTC, secana commented on Readme.md
> +<img src="demo/discord_bot.gif" alt="VaaS Discord Bot" style="width:100%">
Maybe more precise: ... deletes a malicious file on upload on your ...

2022-02-24 14:49 UTC, secana requested changes
Only one small remark in the docs to make it more clear, what the bot does

2022-02-25 17:59 UTC, secana approved these changes

2022-02-28 07:39 UTC, merged