WIP: Perl SDK - adds devcontainer, vaas module and tests
GDATASoftwareAG/vaas pull request #65
Opened 2022-07-14 15:42 UTC by sfotiadis

WIP

2022-08-24 09:23 UTC, unglaublicherdude commented
wait. this isn't WIP anymore, isn't it?

2022-08-24 09:23 UTC, unglaublicherdude commented
ah ok. tests are broken

2022-08-24 10:41 UTC, pstadermann requested changes
My Perl is more than rusty. Just a few things I saw on a quick review.

2022-08-24 10:41 UTC, pstadermann commented on perl/.gitignore
> +.env
.env*

2022-08-24 10:41 UTC, pstadermann commented on perl/src/VaaS.pm
> +    $self->{'ws_client'} = Protocol::WebSocket::Client->new(url => $url);
$self->ws_client =

Search for "$self->{" and replace everywhere.

2022-08-24 10:41 UTC, pstadermann commented on perl/src/VaaS.pm
> +sub get_verdict_by_sha256 {
API is different to all other SDKs.

2022-08-24 10:41 UTC, pstadermann commented on perl/src/VaaS.pm
> +            print "Upload successful.\n";
This will pollute the console of the application using the SDK.

2022-09-21 11:35 UTC, unglaublicherdude commented
Is this still WIP? Please also add an example of how to use the sdk.

2022-11-28 10:48 UTC, secana commented
@sfotiadis this PR seems to be stalled. What should we do with it?

2023-02-20 13:48 UTC, closed without merging